version: '3.2'
services:
  postgres:
    image: "postgres:12"
    command: ["postgres", "-c", "logging_collector=on", "-c", "log_directory=/logs", "-c", "log_filename=postgresql.log", "-c", "log_statement=all"]
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - type: bind
        source: ${POSTGRES_DATA_DIR}
        target: /var/lib/postgresql/data
      - type: bind
        source: ${POSTGRES_LOG_DIR}
        target: /logs
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
