version: '3.2'
services:
  postgres:
    image: "postgres:12"
    logging:
      driver: none 
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - type: bind
        source: ${POSTGRES_DATA_DIR}
        target: /var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
