version: '3.2'
services:
  postgres:
    image: "postgres:12"
    logging:
      driver: none 
    ports:
      - "5432:5432"
    volumes:
      - type: bind
        source: ./volumes/postgres
        target: /var/lib/postgresql/data
    environment:
      - POSTGRES_USER=hello
      - POSTGRES_PASSWORD=world
